env:
  node: true
  commonjs: true
  es2021: true
  jest: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  quotes: ['error', 'single']
  semi: ['error', 'never']
  indent: ['error', 2]
  linebreak-style: ['error', 'unix']
  comma-dangle: ['error', 'always-multiline']
  no-trailing-spaces: ['error']